### ISSUE TITLE
Arduino lab for Scratch documentation

### ISSUE THREAD

**Issue by marcotchella** [arduino/include-robot#1]
Great project
I couldn´t find documentation about [Arduino lab for Scratch](https://labs-scratch.arduino.cc/).
My interest is in learning and extend Scratch. Is there  a repository?
Thank you

**Comment by csarnataro** [comment]
Hi @marcotchella, if you're interested in the Scratch platform itself, I would suggest to have a look at the official Scratch website: https://scratch.mit.edu/

On our hand, we're in the process of adding a few Arduino specific customizations/plugins on top of a standard Scratch installation. We will be improving our docs in the next few weeks.
