### ISSUE TITLE
Update scratch to latest

### ISSUE THREAD

**Issue by csarnataro** [arduino/include-robot#14]

**Comment by dido18** [comment]
Current version  [v.3.2.27](https://github.com/bcmi-labs/scratch-gui/blob/7ddd37b196e58d652dfe7033dde977a59fdc44b3/build-and-patch.sh#L3C17-L3C23)

Latest [v3.6.14](https://github.com/scratchfoundation/scratch-gui/releases/tag/v3.6.14) 

Full diff https://github.com/scratchfoundation/scratch-gui/compare/v3.2.37...v3.6.14
