### ISSUE TITLE
Find a way to pair boards in a class with multiple boards

### ISSUE THREAD

**Issue by csarnataro** [arduino/include-robot#18]
Things to do:
1. configure the BLE name
2. upload the sketch
3. (optional) investigate on specific tools to upload the sketch:
- GUI
- CLI

**Comment by umbynos** [comment]
Subtask:

**Comment by dido18** [comment]
> Subtask:
> 
> * [ ]  make a GUI tool that recognize the board connected to the PC, downloads the correct fw from gh and flashes it.
> * [ ]  make a GH Actions that uploads the fw to the release on GH (https://github.com/arduino/compile-sketches)
> * [ ]  allow the flasher tool to specify some parameter that gets appended to the binary (BLE name for example)

These sub tasks has been done in the installer app
