### ISSUE TITLE
How to make the rubber part for the wheels

### ISSUE THREAD

**Issue by franva** [arduino/include-robot#2]
Hi there,

Thanks for sharing this interesting project and I am wondering that how are we going to make the rubber rim part for the wheels as 3D printer won't be able to print it?
![image](https://user-images.githubusercontent.com/5151146/201826625-e10de544-42a5-4282-aeed-347d4df9ea88.png)

**Comment by csarnataro** [comment]
Hi, this part should be purchased as a separate part.
See for example:
https://www.pololu.com/product/4910

Anyway thank you for opening this issue, I will update the documentation with this information.

**Comment by csarnataro** [comment]
BTW, we're working on the documentation these days, moreover we will add a few`.stl` files in the next few days. This project is still in a very early stage. Stay tuned!
