### ISSUE TITLE
Write a list of scratch blocks (by dividing in sub extension, e.g., Arduino, Sensors, Servo, MiraRobot)

### ISSUE THREAD

**Issue by csarnataro** [arduino/include-robot#3]
Write a list of scratch blocks (by dividing in sub extension, e.g., Arduino, Sensors, Servo, MiraRobot)

**Comment by csarnataro** [comment]
here the document with all defined bloks https://docs.google.com/spreadsheets/d/1FvVz5-000RPJ8xA2ALKzB1U05d9lcgbcC9bPF_HeHIY/edit#gid=0

**Comment by dido18** [comment]
The extension "Arduino Include Robot" has been added.
