### ISSUE TITLE
Define the Arduino robot blocks in the UI

### ISSUE THREAD

**Issue by csarnataro** [arduino/include-robot#4]
See this sheet for further details:
https://docs.google.com/spreadsheets/d/1FvVz5-000RPJ8xA2ALKzB1U05d9lcgbcC9bPF_HeHIY/edit#gid=0

**Comment by csarnataro** [comment]
Block groups:
1. Arduino BLE
2. Sense (ie. all sensors)
3. Myra

**Comment by dido18** [comment]
point 1 was already done.
point 3 was done by adding the `Arduino include robot" extension.


point 2 could be done in the future enhanche
