### ISSUE TITLE
Use the new set two pin message in the block "set the motor angle on pin x and y to angle"

### ISSUE THREAD

**Issue by csarnataro** [arduino/include-robot#6]
## Motivation 
The wheels aren't moving in sync. 
This is because the `move forward` action is translated into two sequential messages (move right wheel + move left wheel). 

## Changes
Move the logic of the robot in the sketch. 

- add a new ble characteristic into the sketch for the robot action.

## Notes
- removed the hardcoded PIN wheel in the JS extension and moved into the Sketch.

**Comment by dido18** [comment]
Currently, Sketch supports the following BLE characteristics:

- `onPinActionCharacteristicWrite` is used to READ action and WRITE ( upon some specific action - read from analog and digital)  a response for a specific PIN. The payload is of the form: `[action, pin, pinValue]`. The action can be: 
     - PINMODE: if the `pinValue=0x4` then attach the servo to the pin, otherwise setup the pin using `pinMode`
     - DIGITALWRITE: write digital `pinValue` to the `pin`
     - DIGITALREAD: read the digital from to the `pin` and write into the response.
     - ANALOGREAD:  read the analog from to the `pin` and write into the response.
     - ANALOGWRITE: write analog `pinValue` to the `pin`
     - SERVOWRITE: find the Servo attached to a `pin` and write the PinValue to it.
     - SERVOWRITE_AND_INITIALIZE: like SERVOWRITE, but if it does not find the Servo it initializes it.
    - SERVOSTOP: find the Servo associated with the `pin` and detach it.
- `onRgbLedCharacteristicWrite` is used to READ an RGB value to switch on the led. Payload is: `[redValue, greenValue, blueValue]`
- `sensorsData` is a NOTIFY characteristic to send different values.
- `versionCharacteristic` to WRITE the version of the sketch
